### ISSUE TITLE
Vaadin Binder Doku should also show how to use ComboBox

### ISSUE THREAD

**Issue by satorstefan** [vaadin/vaadin.com#10]
Hi everyone, 

could you please show how to use the binder and a comboBox in combination?
This page is good: https://vaadin.com/docs/v8/framework/datamodel/datamodel-forms.html
but doesn't cover this case and i could figure it out myself up until now... :-(

It worked now with Strings, but how do i use binder + combobox with "real" businessobjects?

Thanks alot!

**Comment by mickoyuh** [comment]
Hi Stefan, for support questions you could use our Forum or gitter. This github is only for website errors. 

Please check this one, I hope it helps! :) 
https://vaadin.com/blog/forum-chat-and-other-ways-to-connect-with-the-vaadin-community

Mikko

**Comment by satorstefan** [comment]
Hi,

On each website there is the button: Do you miss something.
Why is it there if one should not use it?

Sent from my Windows 10 phone

________________________________
