### ISSUE TITLE
Method in exmaple not the same as in description

### ISSUE THREAD

**Issue by kristofdan** [vaadin/vaadin.com#11]
In the documentation page at [https://vaadin.com/docs/v10/flow/binding-data/tutorial-flow-data-provider.html](url), in the first code listing the `Status::getLabel` method is used to display a `Status`, although the text before the listing tells that `Status.getCaption()` will be used.

**Comment by pleku** [comment]
Thanks for the report. I've moved the issue to the Flow documentation repository, we'll fix it shortly.
