### ISSUE TITLE
Vaadin Spreadsheet - See documentation link is broken.

### ISSUE THREAD

**Issue by Janos-Mucha** [vaadin/vaadin.com#12]
On the page: https://vaadin.com/docs
The "See documentation" link for Vaadin Spreadsheet is broken (404).

**Comment by alvarezguille** [comment]
Thanks for reporting this, there's no Vaadin 10 version of Spreadsheet at the moment, we will fix the link. 
You can check the docs for Spreadsheet 2 compatible with Vaadin 8 in https://vaadin.com/docs/v8/spreadsheet/spreadsheet-overview.html

**Comment by mickoyuh** [comment]
this is fixed, PR waiting to be published.

**Comment by mickoyuh** [comment]
Closing as fixed (removed the wrong link).
