### ISSUE TITLE
org.vaadin.addon.vol3.OLMapElement.class    is missing 

### ISSUE THREAD

**Issue by ramanamuttana** [vaadin/vaadin.com#13]
i am using Testbench to test Opel Layer wrapper with Vaddin 7 , i am getting the following the Web element locator as 
$(org.vaadin.addon.vol3.OLMapElement.class).first();
 the class is missing , Does the class exist ?

**Comment by mickoyuh** [comment]
Hi Ramanamuttana, you've reached the website issue reporting. As you question is more about products would you mind posting this on our forum Testbench area or contacting support through the expert chat? 

https://vaadin.com/forum/category/11572 

Mikko
