### ISSUE TITLE
Unable to logout from vaadin account 

### ISSUE THREAD

**Issue by ramanamuttana** [vaadin/vaadin.com#14]
after having a long  discussion  over  a chat with vaadin customer service  and staying more than four hours of login , i am unable to logout , finally closed all the tabs . Tried on many tabs for logout and also many times on the same tab gave me same result (Unable to logout from account )

**Comment by Haprog** [comment]
Can you tell us what happens if you click on "Log out"? Do you get an error message? Does nothing happen? Which browser are you using?

If nothing else works, you could clear your browser cookies for vaadin.com which should log you out.

**Comment by mickoyuh** [comment]
Hi Ramanamuttana, do you still have this issue?

**Comment by ramanamuttana** [comment]
hi ,
the problem is solved ,thanks a lot
