### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by archenroot** [vaadin/vaadin.com#15]
On page:
https://vaadin.com/docs/v8/framework/getting-started/getting-started-maven.html

there is link to non-existing content:
https://vaadin.com/docs/v8/framework/getting-started-archetypes.html#getting-started.archetypes

**Comment by mickoyuh** [comment]
Thanks, will be checked

**Comment by mikkoi-vaadin** [comment]
https://gitlab.vaadin.com/vaadincom/webpage/issues/3131

**Comment by elmot** [comment]
Already fixed with https://github.com/vaadin/framework/pull/10875

**Comment by mickoyuh** [comment]
This is fixed now.
