### ISSUE TITLE
There is the unclear importance of bundle loading order.

### ISSUE THREAD

**Issue by akvyalkov** [vaadin/vaadin.com#16]
There is the unclear importance of bundle loading order.
Link: https://vaadin.com/docs/v8/framework/advanced/advanced-osgi.html

>Here is a list of required Vaadin bundles, in order of loading:
>jsoup-1.8.3.jar
>gentyref-1.2.0.vaadin1.jar
>vaadin-shared-8.1.x.jar
>vaadin-server-8.1.x.jar-8.1.x.jar
>vaadin-osgi-integration-8.1.x.jar
>vaadin-client-compiled-8.1.x.jar (not required, if your project uses its own widgetset)
>vaadin-themes-8.1.x.jar

Also, If you restart the server, the order is not defined.
And, you may want to change the version of vaadin bundles to 8.x.y, where x in [1,)

**Comment by mstahv** [comment]
Hi @akvyalkov!

I'm not the best expert with OSGi, but your suggestion sounds right. Could you propose a fix directly via GitHub? You can simply edit that with browser and then create a pull request. Our core team will then review the suggestion and the fix should be online pretty soon.

https://github.com/vaadin/framework/edit/master/documentation/advanced/advanced-osgi.asciidoc

This is also maybe the easiest way to become Vaadin contributor ;-)

**Comment by mickoyuh** [comment]
Closing here in favor of the proposed contribution
