### ISSUE TITLE
Broken link for "Layouts in Vaadin 10"

### ISSUE THREAD

**Issue by basil-bourque** [vaadin/vaadin.com#17]
This page:
https://vaadin.com/docs/v10/flow/migration/1-migrating-v8-v10.html
… has a link for "Layouts in Vaadin 10":
https://vaadin.com/5-components.html#Layouts%20in%20Vaadin%2010
… which results in a 404 error.

**Comment by pleku** [comment]
Thanks for the report, I've made a PR which fixes the subheading linking.
