### ISSUE TITLE
Vaadin 10 Designer IntelliJ Idea

### ISSUE THREAD

**Issue by andcdv** [vaadin/vaadin.com#18]
https://vaadin.com/designer/get-started from here going to
https://vaadin.com/docs/v10/designer/designer-installing-idea.html gives 404

**Comment by mickoyuh** [comment]
Team is looking into this now

**Comment by mickoyuh** [comment]
This is fixed and merged. Will be live on next site update today/tomorrow.

**Comment by mickoyuh** [comment]
Works now.
