### ISSUE TITLE
missing semicolon

### ISSUE THREAD

**Issue by jdamianb** [vaadin/vaadin.com#2]
Hello,

I was reading and trying the drag & drop feature and the code on the "Drag & Drop files" is missing a parenthesis and a semicolon. The location is market on the image attached. It is the closing mark for the instruction "files.forEach". I copy/paste this code on Eclipse Oxygen.2 Release (4.7.2). Sorry If I'm completely wrong.

Great library btw!

![2018_04_09_16_16_57_drag_and_drop_vaadin_framework_8_vaadin_8_docs_vaadin](https://user-images.githubusercontent.com/2261304/38503454-6dd6be24-3c12-11e8-8f32-307aca5bb1bb.jpg)

**Comment by mickoyuh** [comment]
Thanks, will be fixed.

**Comment by mikkoi-vaadin** [comment]
https://gitlab.vaadin.com/vaadincom/webpage/issues/3044

**Comment by mickoyuh** [comment]
Forgot to close this after fix. :)
