### ISSUE TITLE
Access denied looking for My thread page

### ISSUE THREAD

**Issue by tullio0106** [vaadin/vaadin.com#22]
I logged on to the Vadin Page but when I try to access the my Thread page I get an erro 403 Access Denied.
If I try to login again it doesn't work.
Tks

**Comment by mickoyuh** [comment]
Hi Tullio, this issue is about access-forbidden page login non-working. Fix is committed already, we will close the issue when it is deployed to live site.

**Comment by mickoyuh** [comment]
This should now be fixed. Closign the issue.
