### ISSUE TITLE
Where to add Jmeter Vaadin Servlet 

### ISSUE THREAD

**Issue by GSRavichandran** [vaadin/vaadin.com#23]
Hi Team,

I am scripting for Vaadin 8 framework based application ,here the button click are going as Client X Y and Relative XY .This particlular components keeps on changing when the button at the time of recording the script is moved to other place based on the user rights.This very critical for us if we are going with the concurrent user load in jmeter which is having button in different position.

Browsed and found the JMeter Vaadin Servlet extension in vaadin forum which would help..

Could anybody from vaadin help to sort this issue or place where we can place the Jmeter Vaadin servlet.

Thanks,
GSR

**Comment by mickoyuh** [comment]
Hi GSR, 

You've reached the website issues repository. Your question looks very much like a forum post. 

Would you mind posting this there, and help the community that way? Someone else in the future will google for your problem and find the solution on the forum. 

Thanks, 
Mikko / Vaadin.com

**Comment by GSRavichandran** [comment]
hi,

what i should do

**Comment by mickoyuh** [comment]
Hi, sorry forgot to add the link. You should post the question here: https://vaadin.com/forum/category/1007558

Thanks, Mikko

**Comment by mickoyuh** [comment]
Closing this here
