### ISSUE TITLE
Grid Element HTML API documenation is empty

### ISSUE THREAD

**Issue by mattMillerC** [vaadin/vaadin.com#24]
The HTML API documentation page for the [Vaadin.GridElement](https://vaadin.com/components/vaadin-grid/html-api/elements/Vaadin.GridElement) is blank. (https://vaadin.com/components/vaadin-grid/html-api/elements/Vaadin.GridElement)

Expected to see full documentation including element's description, properties, methods and events.

Actually seeing documentation page without any information.

![screen shot 2018-05-11 at 10 56 26 am](https://user-images.githubusercontent.com/6796374/39931225-c698f39a-550a-11e8-981b-bd2bc5cbc3b6.png)

Possibly related, the [HTML api listing page for Vaadin Grid](https://vaadin.com/components/vaadin-grid/html-api) is missing the link to the Vaadin.GridElement.
(https://vaadin.com/components/vaadin-grid/html-api)

![screen shot 2018-05-11 at 11 02 32 am](https://user-images.githubusercontent.com/6796374/39931254-d8c25264-550a-11e8-9cce-c6b8db7d2255.png)

**Comment by mickoyuh** [comment]
Thanks Matt, We have also identified the same last week. There is an update to the site coming up today that should fix this.

**Comment by mickoyuh** [comment]
This is now fixed.
