### ISSUE TITLE
Push Vaadin8 on Liferay7

### ISSUE THREAD

**Issue by mltpz** [vaadin/vaadin.com#26]
Dear all,
Pushing mechanism described in [https://vaadin.com/docs/v7/framework/advanced/advanced-push.html](url) doesn't work in Liferay7.
Is there any solution/workaround?

**Comment by mickoyuh** [comment]
Hi mltpz, 

For technical discussion which is not a website bug, please use Vaadin community forum https://vaadin.com/forum

Thanks!
Mikko
