### ISSUE TITLE
Vaadin 8.3 and 8.4 missing in Addon Supported Framework selection

### ISSUE THREAD

**Issue by mcollovati** [vaadin/vaadin.com#27]
When setting `Supported Frameworks` using `Upwards from` or `Specific version` framework versions 8.3 and 8.4 are not available; only 8.0, 8.1 and 8.2 are present.

![sc2](https://user-images.githubusercontent.com/4648894/40140257-bff42608-5952-11e8-9cd3-b7814f93d6a7.png)
![sc1](https://user-images.githubusercontent.com/4648894/40140258-c019cf0c-5952-11e8-8e9d-c65f97524068.png)

**Comment by paulroemer** [comment]
Thanks for pointing that out! 

Fix is applied. Can you try again and close the issue if it works?

Cheers,
  Paul

**Comment by mcollovati** [comment]
I'm not yet able to see 8.3 and 8.4; maybe some cache issue?
Will try again later

**Comment by mcollovati** [comment]
It works now, thanks.
