### ISSUE TITLE
Java example for vaadin-icons shows all available icons on a single line with only the first few  visiable

### ISSUE THREAD

**Issue by rossms4** [vaadin/vaadin.com#29]
The "All available icons" example for vaadin-icons tries to display all the icons on the one line with only the first few visible. The rest are off the page but if you scroll right they are the same colour as the background and hence not visible.
https://vaadin.com/components/vaadin-icons/java-examples

**Comment by pleku** [comment]
Thanks for the report. We will fix it ASAP.

**Comment by paulroemer** [comment]
Fixed.
