### ISSUE TITLE
Invalid link for customer.java in tutorial

### ISSUE THREAD

**Issue by helloingob** [vaadin/vaadin.com#3]
The link "**Customer.java**" in "**3. Adding a demo "backend**"" from the [tutorial](https://vaadin.com/docs/v10/flow/introduction/tutorial-get-started.html) is missing a "**/**" (slash) after the TLD => "https://raw.githubusercontent.comvaadin/flow-and-components-documentation/master/tutorial-getting-started/src/main/java/com/vaadin/flow/demo/helloworld/Customer.java"

**Comment by mikkoi-vaadin** [comment]
https://gitlab.vaadin.com/vaadincom/webpage/issues/3045

**Comment by maximeVaadin** [comment]
It's now fixed. Thanks !
