### ISSUE TITLE
Missing PDF Book of Vaadin

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/vaadin.com#30]
The "get it here" links do not initiate the download:
https://vaadin.com/docs/v7/index.html
https://vaadin.com/docs/v8/index.html

**Comment by javier-godoy** [comment]
The links are working now. Thank you.

**Comment by edler-san** [comment]
The links are broken again. Please reopen the ticket.

**Comment by samie** [comment]
Link in section "Looking for the Book of Vaadin?" is still not working.

**Comment by mickoyuh** [comment]
There was an issue with page revisions that caused this to not load correctly. Fixed this morning.
