### ISSUE TITLE
In the vaadin-list-box HTML please include an example using items property 

### ISSUE THREAD

**Issue by chisholmd** [vaadin/vaadin.com#31]
In the vaadin-list-box HTML please include an example using items property

**Comment by mickoyuh** [comment]
Submitted the issue to product team

**Comment by jouni** [comment]
Answered here: https://github.com/vaadin/vaadin-list-box/issues/34#issuecomment-395317841

Basically, there’s no `items` property, so there’s no example to add.

**Comment by mickoyuh** [comment]
Closing as nothing more to be done.
