### ISSUE TITLE
no way to download the sample

### ISSUE THREAD

**Issue by felixvolz** [vaadin/vaadin.com#32]
no way to download starter sample - download button is disabled

![image](https://user-images.githubusercontent.com/6946906/40469817-07f66ef2-5f75-11e8-9fce-fc65572ca389.png)

**Comment by felixvolz** [comment]
okay I reloaded the page and then a tick box appeared and the project downloaded

**Comment by paulroemer** [comment]
Great you find it. I already tested and the checkbox was visible to me at first try.

It feels like the checkbox webcomponent could not be loaded but the /start view has the expected imports.

Is it in any way reproducable for you?

**Comment by felixvolz** [comment]
I retried in a google chrome incognito mode and couldnt reproduce. 

Initally occured with Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by mickoyuh** [comment]
Not reproducible
