### ISSUE TITLE
404 in v10 docs -> Vaadin Components -> Getting started

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin.com#34]
The link "Getting started" under "Vaadin Components" section leads to 404. The broken link is [https://vaadin.com/components/get-started](https://vaadin.com/components/get-started).

**Comment by mickoyuh** [comment]
Submitted to Docs team. Thanks!

**Comment by ZheSun88** [comment]
verified with @mehdi-vaadin this issue is not valid any more. 
this one https://github.com/vaadin/flow-and-components-documentation/issues/178 will be closed.
