### ISSUE TITLE
Vaadin 10 Addons won't be uploaded

### ISSUE THREAD

**Issue by appreciated** [vaadin/vaadin.com#35]
My two recently added Vaadin addons do not seem to get uploaded to the Maven server. I'm not getting any error messages so I have no idea what it could be. I'd be glad to get some help fixing this. 

The addons were both created via the [Add-on Component Starter](https://vaadin.com/start/v10-component)

![addon1](https://user-images.githubusercontent.com/1729845/40686664-64103502-6398-11e8-8051-66dce74a95f3.PNG)
![addon2](https://user-images.githubusercontent.com/1729845/40686665-6429b108-6398-11e8-96af-f03058f84c0f.PNG)

**Comment by samie** [comment]
Most typical reason is that Maven deployment requires a valid license to be present. 

Unfortunately there is no force check for this one, but you can choose the license in Versions tab when editing the component in Directory. Could you try that and let us know how that goes?

**Comment by appreciated** [comment]
Hi @samie! Thank you for your response, that worked pretty much immediately. To avoid such "stupid" user mistakes in future it might be a good idea to force the user to select a license when checking the publish switch by disabling the save button.

**Comment by samie** [comment]
Good to hear. I agree this needs some save time checks, so I forwarded this to the web site team to take care of.

**Comment by mickoyuh** [comment]
Closing this here as the original issue was fixed. We have improvement item in the backlog.
