### ISSUE TITLE
Waterfall Charts

### ISSUE THREAD

**Issue by oneaxxall** [vaadin/vaadin.com#36]
Waterfall Charts Documentation is not complete , I'am so confused what should i do .

**Comment by mickoyuh** [comment]
Submitted to docs team. Thanks!

**Comment by oluwasayo** [comment]
Fixed in https://github.com/vaadin/vaadin-charts-flow/issues/192

**Comment by mickoyuh** [comment]
Still needs to be deployed to production build.

**Comment by Haprog** [comment]
@visualandcode Could you tell us which pages were you looking at for the documentation? Were you looking for documentation of the Java API or the HTML API?

I think the above mentioned change https://github.com/vaadin/vaadin-charts-flow/issues/192 might not be related or might not make things much better depending on what you were trying to find and where.

The change above only affects this page: https://vaadin.com/docs/v10/charts/java-api/charts-charttypes.html#charts.charttypes.waterfall But if that's exactly what you were looking for, then we can probably close this issue once the change has been deployed to vaadin.com.

**Comment by mickoyuh** [comment]
Seems fixed, nothing more clear to be done.
