### ISSUE TITLE
Get-started-tutorial doesn't match the latest API

### ISSUE THREAD

**Issue by mehrdad001** [vaadin/vaadin.com#37]
Please update your site so the code you have provided on the site for your tutorial matches the latest API. Obviously, it defeats the whole purpose if your code doesn't compile against the latest API, and the sample code cannot be run.

**Comment by mickoyuh** [comment]
Hi, could you point out which tutorial you found this issue with?

**Comment by mickoyuh** [comment]
Closing as unclear
