### ISSUE TITLE
vaadin-grid pagination not worked

### ISSUE THREAD

**Issue by sudhamohanpanda** [vaadin/vaadin.com#38]
Dear Vaadin team,

First let me thanks you for your excellent work.
I am using polymer 3 
I have install vaadin-grid using npm.

If I copy the code from "Basic Usage" it's working fine.

But when I copy the code from "Pagination" it NOT working for me. Do anything else I have to do?

**Comment by mickoyuh** [comment]
Hi there, 

You've reached the website issue reporting. :) 

For technical questions I would propose to use the Vaadin community forum: 
https://vaadin.com/forum/category/1007558/framework

This allows the community to contribute to the question and also stores the answer for anyone looking for similar help. 

Thanks! Mikko
