### ISSUE TITLE
Incorrect URL in vaadin-ordered-layout page

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin.com#39]
It seems that there is a mistake in the Overview section of [vaadin-ordered-layout](https://vaadin.com/components/vaadin-ordered-layout/) page in Components section. 
At the bottom of the page where importing is described, an incorrect URL is used in `href` attribute of `link` tag; the incorrect URL is `"bower_components/vaadin-ordered-layout/vaadin-ordered-layout.html"` that doesn't exist and the correct URLs based on this [link](https://github.com/vaadin/vaadin-ordered-layout) are: 
`"bower_components/vaadin-ordered-layout/vaadin-horizontal-layout.html"` and 
`"bower_components/vaadin-ordered-layout/vaadin-vertical-layout.html"`. 
I'm talking about Polymer 2 version but I would check Polymer 3 as well.

**Comment by mickoyuh** [comment]
Thank you, I've reported this to the website team to fix.

**Comment by mickoyuh** [comment]
Closing as this is team internal report
