### ISSUE TITLE
vaadin 8 There's no way around it TreeGrid

### ISSUE THREAD

**Issue by qq157447342** [vaadin/vaadin.com#40]
vaadin 8 There's no way around it TreeGrid

**Comment by mickoyuh** [comment]
could you please explain a bit more. What is the problem?

**Comment by qq157447342** [comment]
sorry , my English is so bad .....  
new TreeGrid() have a Exception :
java.lang.NoSuchMethodError:com.vaadin.data.provider.HierarchicalDataCommunicator.getBackEndSorting()Ljava/util/List;     
What might be the reason...
@mikkoi-vaadin
