### ISSUE TITLE
SizeReporter page is missing

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/vaadin.com#41]
https://vaadin.com/directory#!addon/sizereporter  is missing.
https://vaadin.com/directory/search?keyword=SizeReporter shows the plate of SizeReporter, but link on the plate goes nowhere

**Comment by Haprog** [comment]
I can't reproduce your issue.
https://vaadin.com/directory#!addon/sizereporter is a legacy URL which correctly redirects to https://vaadin.com/directory/component/sizereporter
The search page also links to https://vaadin.com/directory/component/sizereporter which seems to be working fine.
