### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by mastre-pad** [vaadin/vaadin.com#43]
I read docs for Vaadin 10 and couldnot find system requirements - what browsers it requires?
Starter project doesnot start in Firefox 38...

It's important to know what environment Vaadin 10 needs when planning application for intranet.

**Comment by mickoyuh** [comment]
Hi there, Vaadin 10 browser requirements are the same as in Vaadin Framework 8 so basically, it's going to be Internet Explorer 11 or better. We recommend deploying Vaadin 10 applications to evergreen browsers such as Microsoft Edge, Google Chrome or Apple Safari.

**Comment by mickoyuh** [comment]
And if you have further questions or comments on this topic, I would recommend to visit our forum and support the Vaadin community. Thanks! :)
