### ISSUE TITLE
HTML Example of Date Picker not aligned with Sidebar

### ISSUE THREAD

**Issue by knoobie** [vaadin/vaadin.com#45]
HTML Examples doesn't align to its Sidebar, see Screenshot for Version of FF.

URL: https://vaadin.com/components/vaadin-date-picker/html-examples/date-picker-basic-demos

Removing the following, fixed the alignment for me.  

```
.sidebar.vc-layout-sidebar {
    width: calc(var(--sidebar-width) + 0.5 * (100vw - var(--container-width)));
}
```

![bildschirmfoto_2018-06-20_09-38-41](https://user-images.githubusercontent.com/3968629/41644326-0773b5c6-746e-11e8-9b6a-80e326023e3e.png)

**Comment by mickoyuh** [comment]
Thanks for reporting this. I have sent the issue to website team to fix.

**Comment by mickoyuh** [comment]
This is now fixed as we rewrote the components pages.
