### ISSUE TITLE
Placeholder in combobox disappears when setEnabled(false).

### ISSUE THREAD

**Issue by MrManc14** [vaadin/vaadin.com#47]
My goal is to query a database to displays values in the drop down list of the combobox. However, if there are no values returned I would like to display, in a placeholder, "No options" and then disable the combobox; so the user can't click again.

When I disable the combobox it makes the placeholder disappear. Is there a way to disable the combobox and keep the placeholder value? Or perhaps an alternate (getting rid of the combobox and replacing the component with a label)?

Much thanks.

**Comment by MrManc14** [comment]
A similar solution I found for this:
                    select.setEmptySelectionCaption("No versions"); //instead of placeholder
                    select.setEnabled(false);

This displays the text and disables the combobox.

**Comment by mickoyuh** [comment]
You've reached the website feedback. :) Sorry for late response. 

Please use vaadin.com/forum for technical questions.
