### ISSUE TITLE
Getting started with Microservices blog missing

### ISSUE THREAD

**Issue by jroneil** [vaadin/vaadin.com#49]
This  was a very good tutorial

**Comment by Haprog** [comment]
@jroneil do you mean this one? https://vaadin.com/blog/getting-started-with-microservices

Doesn't seem to be missing to me. Or do you think there was some other blog post you were looking for related to microservices?

**Comment by Haprog** [comment]
Or maybe you were looking for this (not really a blog post but multi-page learning resource about microservices)? https://vaadin.com/microservices

**Comment by mickoyuh** [comment]
Closing as this seems to be answered
