### ISSUE TITLE
Valo theme installation

### ISSUE THREAD

**Issue by mltpz** [vaadin/vaadin.com#5]
Dear all,
https://vaadin.com/docs/v8/framework/themes/themes-valo.html page doesn't explain how to install Valo Theme in Liferay 7
In my portlets, theme is not loaded and Liferay reports an error 404 during portlet execution.
Could you please explain how to install Valo theme in Liferay 7?
Regards

**Comment by mickoyuh** [comment]
Hi, this github is for website issue reporting. 

For community support you might want to post on our Forum or try the gitter option: 
https://vaadin.com/blog/forum-chat-and-other-ways-to-connect-with-the-vaadin-community

Thanks, 
Mikko

**Comment by mltpz** [comment]
I clicked on link "Missing something on this page?Report it here" at the end of page https://vaadin.com/docs/v8/framework/themes/themes-valo.html to arrive here

**Comment by mickoyuh** [comment]
Ah I can see. It means if you encountered a bug or broken link etc. 

Anyway, please go to forum for the question where we have the discussion. 

Thanks, Mikko
