### ISSUE TITLE
Dropdown Menu Component Java API Link Broken

### ISSUE THREAD

**Issue by bdaroz** [vaadin/vaadin.com#50]
On: https://vaadin.com/components/vaadin-dropdown-menu

The link to the Java API on the bottom left is broken. It links to https://demo.vaadin.com/javadoc/com.vaadin/vaadin-core/10.0.1/index.html?com/vaadin/flow/component/dropdown-menu/Dropdown-menu.html

**Comment by Haprog** [comment]
Thanks for the report. Dropdown menu doesn't actually have a Java API (at least not yet) so the link is incorrectly shown. Same issue affects some other components also (at least Context menu).

We will fix this issue (to remove the incorrect Java API link) soon.

**Comment by mickoyuh** [comment]
Fixed
