### ISSUE TITLE
A mistake in polymer app generator package name

### ISSUE THREAD

**Issue by dtsaryov** [vaadin/vaadin.com#51]
1. Go to Polymer starter pack page: [link](https://vaadin.com/start/v10-polymer)
2. Check second step

![image](https://user-images.githubusercontent.com/6183810/41892796-7f69df22-792a-11e8-9f50-ca3d8f5525ea.png)

While it should be `generator-polymer-init-vaadin-elements-app`

**Comment by mickoyuh** [comment]
Thanks! I will let the app generator team know.

**Comment by mickoyuh** [comment]
Moved to another repository

**Comment by mickoyuh** [comment]
Fixed in development, will be visible when we deploy.
