### ISSUE TITLE
Vaadin 10 - Password Field Component link leads to Text Field

### ISSUE THREAD

**Issue by fufex79** [vaadin/vaadin.com#52]
When browsing the 24+ Components page, if you click on the picture for Password Field you are redirected to https://vaadin.com/components/vaadin-text-field
I tried entering https://vaadin.com/components/vaadin-password-field directly into the browser but then I got 404.

**Comment by Haprog** [comment]
This is intended. The password field is a variation of the text field. They're bundled in the vaadin-text-field package. We could improve the contents of the text field page to make this more obvious though.

**Comment by fufex79** [comment]
Well, I understand. But for me it was confusing. Because of the website I thought there is no extra class for password fields so I wasted five minutes trying finding out how to set a Textfield as Passwordfield. I was searching for a method on Textfield like field.setAsPasswordField() etc.
When I found nothing I came to the idea that there may be an own class. And voila, there it was. But maybe it is just me and I was thinking too complicated :)

**Comment by Haprog** [comment]
I agree this is a bit confusing, especially from Java API point of view. From HTML API point of view they're bundled in the `vaadin-text-field` package (at least currently, though this might change in the future) that you would need to install (if using the component separately without Flow).

**Comment by mickoyuh** [comment]
Closing as answered
