### ISSUE TITLE
How to correctly deploy app in IE11

### ISSUE THREAD

**Issue by ebatgerel** [vaadin/vaadin.com#54]
Hello, I have problem with flow. When i start my website and using IE 11 its gives me white screen. But contents rendered. I used `mvn spring-boot:run -Dvaadin.productionMode` its compiled succes. But in IE11 its not working. What did i do wrong ? Any advice ? 

![ie](https://user-images.githubusercontent.com/16677052/42257968-e9e5e4c4-7f8b-11e8-9c69-a7774bdf6700.PNG)

**Comment by paulroemer** [comment]
Hi ebatgerel,

which project did you try? One of our starters or did you create a new one from scratch?

-Paul

**Comment by ebatgerel** [comment]
I started new one.

**Comment by mickoyuh** [comment]
Please ask the technical questions on our vaadin.com/forum. This repository is for site bug reporting. 

thanks! :)
