### ISSUE TITLE
Malfunction in search documents

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin.com#55]
![vaadin search error](https://user-images.githubusercontent.com/32511762/42311601-e57e21e2-8046-11e8-8166-86b0773a6ab4.png)
In [documentation page](https://vaadin.com/docs/) of vaadin.com when a text is entered in search text-input the list is filtered based on the given text. But, after the text is changed to something else, filtering doesn't work and it's still filtered by the old text.

**Comment by mickoyuh** [comment]
Team internal report, moving to another repository.
