### ISSUE TITLE
API Javadocs for Vaadin 7.x versions 7.7.4 and later are not accessible

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/vaadin.com#62]
Where are the API Javadocs for e.g. Vaadin 7.7.13? I can't find them.

Finding any 7.x at all requires manually editing the URL. There are no 7.x releases listed in the normal pull-down.

**Comment by paulroemer** [comment]
Hey @archiecobbs,

sorry for the late response but here it is: https://vaadin.com/api/framework/7.7.14/overview-summary.html

Cheers

**Comment by archiecobbs** [comment]
@paulroemer, thanks!
