### ISSUE TITLE
API Javadoc missing "package-list"

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/vaadin.com#63]
It's no longer possible to link to Vaadin's API Javadoc from another project's generated Javadoc because you have done something terrible to the `package-list` file which makes this possible:
```
wget https://vaadin.com/api/platform/10.0.4/package-list
--2018-09-01 18:15:00--  https://vaadin.com/api/platform/10.0.4/package-list
Resolving vaadin.com... 104.20.35.243, 104.20.36.243
Connecting to vaadin.com|104.20.35.243|:443... connected.
HTTP request sent, awaiting response... 404 
2018-09-01 18:15:02 ERROR 404: (no description).
```
Please put it back unharmed. Thanks.

If you are unfamiliar with `package-list`, see [this link](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#package-list).

**Comment by fluorumlabs** [comment]
`package-list` is now made accessible :)
