### ISSUE TITLE
Invalid link on checkout page (404)

### ISSUE THREAD

**Issue by stefanroeck** [vaadin/vaadin.com#64]
On https://sites.fastspring.com/vaadin/product/subscription_prime_yearly and https://sites.fastspring.com/vaadin/product/subscription_pro_yearly the link to the pro-tools page is dead and results in a 404.
![image](https://user-images.githubusercontent.com/1036613/45203133-6cbf5480-b27b-11e8-8eb1-a5a400bf42af.png)

You're welcome :-)

**Comment by mickoyuh** [comment]
Thank you Stefan, I will pass it for the website team to fix asap. :)

**Comment by Haprog** [comment]
There's no 404 here anymore so closing as fixed.

Even though the link doesn't make much sense as it refers to old page that is not available as is anymore (so it is redirected to some related page instead). But the whole purchasing experience will be updated pretty soon and you won't see this same text and link then anymore, so it won't matter soon.
