### ISSUE TITLE
Admonitionblock Tip styling of links in iOS 12.1 Portrait-Mode

### ISSUE THREAD

**Issue by knoobie** [vaadin/vaadin.com#67]
Found a funny styling glitch while studying your docs on my iPhone XS (iOS 12.1) - on Portrait Mode it was not possible to read the text of the link in the tip box. On Landscape anything was readable again (turning the phone or refresh the side doesn't changed a thing.)

URL: https://vaadin.com/docs/flow/creating-components/tutorial-component-basic.html

Portrait Mode: 
![portrait](https://user-images.githubusercontent.com/3968629/50084454-55d3bb00-01f7-11e9-887a-78ac6b0e62c9.jpeg)

Landscape Mode:
![landscape](https://user-images.githubusercontent.com/3968629/50084459-58361500-01f7-11e9-8e1c-b757ac147a1b.jpeg)

**Comment by Haprog** [comment]
Thank you for the report. A fix is on the way. Should be in production in a day or two.

**Comment by Haprog** [comment]
This was fixed before Christmas, but forgot to close the issue. Seems to be working fine now, so closing as fixed.
