### ISSUE TITLE
API Javadoc broken (again): clicking on package does not show package classes

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/vaadin.com#68]
Clicking on a Java package in the upper left frame fails to cause the lower left frame to reload with that package's classes.

As a result, the lower left frame always shows "All classes", which makes it useless because that's so many.

Steps to reproduce (for example):
1. Load https://vaadin.com/api/framework/8.6.2/overview-summary.html
1. Click on `com.vaadin.annotations` in upper left frame
1. Notice that the lower left frame does not reload

This relates to #61...

_Please stop changing the API Javadocs in a way that is broken/unfamiliar to Java programmers_

_You closed #61 yet you did not provide a normal API Javadoc build - could you please provide one?_

**Comment by fluorumlabs** [comment]
Hi @archiecobbs,

Thank you for reporting, this is clearly a regression. I'll personally take a look at it.

In the meanwhile, you can use ["classic" javadoc for Framework 8](https://vaadin.com/download/release/8.6/8.6.2/docs/api/).

**Comment by archiecobbs** [comment]
@fluorumlabs, thanks!

**Comment by fluorumlabs** [comment]
Subclasses are now shown when package is selected on the left pane
