### ISSUE TITLE
Vaadin.com is dead

### ISSUE THREAD

**Issue by dinumihnea** [vaadin/vaadin.com#69]
The website is not available.
![image](https://user-images.githubusercontent.com/20513656/53720798-449b6180-3e6a-11e9-8eb4-841a41d82d1b.png)
Also all documentation, demos, and license are unavailable.

**Comment by gilberto-torrezan** [comment]
We are facing some problems in the infrastructure at the moment, it will come back soon.

Sorry for the inconvenience.

**Comment by Shridhad** [comment]
Vaadin.com is back alive.
