### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by helloingob** [vaadin/vaadin.com#7]
1) Navigate to https://vaadin.com/docs
2) Search for "blank" in "Search for a subject" box (Version doesn't matter)
3) Click on "Show more results from the entire book…"
4) https://vaadin.com/search?q=blank is opened
5) 404 :<

**Comment by binbalenci** [comment]
Hi @helloingob, thanks for the bug report. I have added this problem to the team's ticket. At the moment, the link is broken no matter for any unmatched keywords. We will have a look at this asap.

Cheers!

**Comment by mikkoi-vaadin** [comment]
https://gitlab.vaadin.com/vaadincom/webpage/issues/3076

**Comment by mickoyuh** [comment]
This is now fixed in development
