### ISSUE TITLE
Typo in tutorial code block

### ISSUE THREAD

**Issue by gurtjun** [vaadin/vaadin.com#77]
I was going through the [Reactive Chat App with Spring Boot, Project Reactor, and Vaadin](https://vaadin.com/tutorials/reactive-chat-app) tutorial when I noticed that there is a typo in the following code block:

```java
public MainView() {
  setSizeFull();
  setDefaultHorizontalComponentAlignmen(Alignment.CENTER);
  addClassName("main-view");

  H1 header = new H1("Vaadin Chat");
  header.getElement().getThemeList().add("dark"); (1)

  add(header);
}
```

It should be `setDefaultHorizontalComponentAlignment` i/o `setDefaultHorizontalComponentAlignmen`.

**Comment by gurtjun** [comment]
Same for the following code block:

```java
@Bean
UnicastProcessor<ChatMessage>publisher(){
    return  UnicastProcessor.create();
}
@Bean
Flux<ChatMessage> message(UnicastProcessor<ChatMessage publisher) {
    return publisher.replay(30).autoConnect();
}
```

Should be:
```java
@Bean
UnicastProcessor<ChatMessage>publisher(){
    return  UnicastProcessor.create();
}
@Bean
Flux<ChatMessage> messages(UnicastProcessor<ChatMessage> publisher) {
    return publisher.replay(30).autoConnect();
}
```

**Comment by gurtjun** [comment]
Also, CSS in `styles.css` won't work without adding `@StyleSheet("frontend://styles/styles.css")` to `MainView.java`. This is not mentioned in the tutorial.

**Comment by gilberto-torrezan** [comment]
Thanks @gurtjun for the report! We will fix those asap.

**Comment by marcushellberg** [comment]
Thanks for pointing these out! 

I fixed the code snippets, they should be updated on the site shortly. I think I have some sort of issue with my code formatting, as I've had problems with similar missing characters in other tutorials as well
