### ISSUE TITLE
Messy styling in Vaadin Docs

### ISSUE THREAD

**Issue by Andelous** [vaadin/vaadin.com#78]
Hello, I was visiting the docs, just as usual, and noticed the styles were kind of messing up in the pages.

The most obvious issue is a white box around green text (Probably just `String`'s).

Here is an example
https://vaadin.com/docs/v10/flow/routing/tutorial-routing-annotation.html

- Chrome Versión 74.0.3729.169 (Build oficial) (64 bits)
- Firefox Quantum 62.0.2 (64-bit)

![chrome](https://user-images.githubusercontent.com/20797586/58291448-0c2d6480-7d83-11e9-8f5c-71766058c45a.png)

![ff](https://user-images.githubusercontent.com/20797586/58291449-0c2d6480-7d83-11e9-8535-fbdd710006fe.png)

**Comment by Shridhad** [comment]
Thanks @Andelous  for reporting. The styles have been fixed.
