### ISSUE TITLE
Vaadin Flow - Get Started page link may be incorrect

### ISSUE THREAD

**Issue by stephen-howell** [vaadin/vaadin.com#8]
On the page https://vaadin.com/flow/get-started  
The link under Full stack app starter goes to https://vaadin.com

**Comment by mickoyuh** [comment]
Thanks Stephen, that needs to be changed to https://vaadin.com/start/v10-full-stack-spring 

I will file an issue for that.

**Comment by paulroemer** [comment]
We decided to remove the whole page as it was deprecated anyway and added a redirect. Google already updated its index.

Thanks!
