### ISSUE TITLE
Logging in in order to use framework

### ISSUE THREAD

**Issue by tristan957** [vaadin/vaadin.com#81]
I am trying to use Vaadin 14 and have setup a little dummy application with Spring Boot. Am I really expected to create an account and sign in to use Vaadin?

**Comment by gilberto-torrezan** [comment]
Hi Tristan,

Are you referring to the Full Stack App starter template for Spring in vaadin.com/start? That one is commercial, so it's gated behind the login/signup.

But you can get started with Vaadin with Spring Boot without being logged in, by downloading this starter mentioned in the [quick start tutorial](https://vaadin.com/tutorials/vaadin-quick-start): https://vaadin.com/start/latest/project-base

**Comment by tristan957** [comment]
I just started with a Spring Initializr project, and grabbed the code you linked. I am fairly certain that I also had `@PWA` as well.

**Comment by Artur-** [comment]
At what point do you need to log in? Commercial components require a trial or license and will ask you to log in. The framework itself and free (i.e. most) components do not

**Comment by tristan957** [comment]
As soon as I visited the site in my spring boot application. No matter though. I have decided upon a different route.

I had the example from the second site. I believe I was also importing horizontal layout as well.
