### ISSUE TITLE
Annotations in Vaadin Directory javadoc are difficult to read

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/vaadin.com#83]
CSS class "token annotation puntuation" in Vaadin Directory javadocs is styled with #f8f8f2 color over #f1f1f1 background, which is difficult to read. 

See, for instance: 
https://vaadin.com/api/com.flowingcode.addons/iron-icons/1.0.1/com/flowingcode/vaadin/addons/ironicons/EditorIcons.Icon.html

![image](https://user-images.githubusercontent.com/11554739/63783599-a7befb80-c8c3-11e9-8701-69b056f7e22a.png)

**Comment by binbalenci** [comment]
Hi @javier-godoy, thank you for reporting this to us. The API is actually on a different service than Directory. I will take this matter to the team and will inform you when it has been fixed.

**Comment by javier-godoy** [comment]
Fixed. Thank you.

![image](https://user-images.githubusercontent.com/11554739/65914383-b0fe2500-e3a7-11e9-8dcb-3e9cc1e76f74.png)
