### ISSUE TITLE
IOs Google App not supported 

### ISSUE THREAD

**Issue by knoobie** [vaadin/vaadin.com#86]
Visiting Vaadin.com with the Google App under the latest IOs is not possible. That's a huge downer for every new customer or potential person that looks for Vaadin "quick/on the go". I don't want to be forced to use safari for some simple documentation lookups. 

![4F6EAE5F-49F3-4DB3-847B-6D86EA29FA4F](https://user-images.githubusercontent.com/3968629/69400793-44423f80-0cf3-11ea-9387-58eb2b08da9f.png)

**Comment by fluorumlabs** [comment]
Interesting. Could you please share your User Agent (https://www.google.com/search?q=my+user+agent)

**Comment by knoobie** [comment]
Of course, here we go: 

![F90B5155-EF04-49DF-8826-4601DEE2A2AB](https://user-images.githubusercontent.com/3968629/69411968-4cf43f00-0d0e-11ea-8fe3-8fcac38eb831.png)

**Comment by gilberto-torrezan** [comment]
Hey @knoobie thanks for the report.

We will update the website as soon as possible to support this browser. Sorry for the inconvenience.

**Comment by knoobie** [comment]
Closing this issue, browser is working - thanks for the update!
