### ISSUE TITLE
Javadoc API discourages usage of V14

### ISSUE THREAD

**Issue by knoobie** [vaadin/vaadin.com#88]
Reading your latest mail:

> As a cutting-edge release, Vaadin 15 is mainly intended for developers and teams looking to explore and familiarize themselves with our latest feature implementations. The latest LTS release recommended for long-term production deployment is currently Vaadin 14.

it feels discouraging to use V14 as LTS product when even the API Docs tell me to go to the "cutting-edge" release. 

![image](https://user-images.githubusercontent.com/3968629/76069517-41faad00-5f93-11ea-9d4d-704da02adbcc.png)

Example: https://vaadin.com/api/platform/14.1.18/com/vaadin/flow/component/Html.html

**Comment by paulroemer** [comment]
Thanks for reporting! We know about the issue and working on it. Same is true for our Vaadin 14 docs right now.

**Comment by paulroemer** [comment]
Fixed

**Comment by knoobie** [comment]
Thanks! Looks good!
