### ISSUE TITLE
vaadin.com/blog contains TEST between every blog post

### ISSUE THREAD

**Issue by knoobie** [vaadin/vaadin.com#89]
There is a visual TEST between every blog post on [vaadin.com/blog](https://www.vaadin.com/blog). 

![image](https://user-images.githubusercontent.com/3968629/79065818-77419b80-7cb3-11ea-806f-24e8e5fea4d4.png)

![image](https://user-images.githubusercontent.com/3968629/79065791-4c574780-7cb3-11ea-8833-f38935b8543a.png)

**Comment by sshmhh** [comment]
Thanks for reporting, it's fixed now.
