### ISSUE TITLE
Vaadin Flow Get Started Maven example

### ISSUE THREAD

**Issue by stephen-howell** [vaadin/vaadin.com#9]
On the page https://vaadin.com/flow/get-started

In the Hello World sample Maven command:

mvn -B archetype:generate -DarchetypeGroupId=com.vaadin -DarchetypeArtifactId=TODO -DarchetypeVersion=LATEST -DgroupId=org.test -DartifactId=vaadin-app -Dversion=1.0-SNAPSHOT

There is a TODO, Maven can't find a vaadin archetype for TODO, is it a placeholder perhaps?

**Comment by pleku** [comment]
That page should not exist. The getting started link now in https://vaadin.com/flow points to correct page, which is https://vaadin.com/start#vaadin10.

We need to remove this page also.

**Comment by mstahv** [comment]
It is not there anymore, closing.
