### ISSUE TITLE
Example Code in Releases is hard to read

### ISSUE THREAD

**Issue by knoobie** [vaadin/vaadin.com#93]
Example Page: https://vaadin.com/releases

Screenshot: (Firefox 77)

![image](https://user-images.githubusercontent.com/3968629/82678599-27f37100-9c4a-11ea-9e80-39c0f7eb1a7d.png)

**Comment by knoobie** [comment]
Now firefox looks like this:
![image](https://user-images.githubusercontent.com/3968629/82866062-75acf980-9f28-11ea-9aa7-c0c9d0cb2577.png)

And chrome:
![image](https://user-images.githubusercontent.com/3968629/82866041-69c13780-9f28-11ea-8004-c1408f6921ae.png)

**Comment by sshmhh** [comment]
Thanks for the report. We had some styles issues on the website recently due to css migration, now it should be fine again.

**Comment by knoobie** [comment]
It looks more readable, but not as good as (for example) the examples you public in your docs: 
![image](https://user-images.githubusercontent.com/3968629/83010835-2abedf00-a019-11ea-9a56-a17ab089fc94.png)
https://vaadin.com/components/vaadin-combo-box/java-examples

![image](https://user-images.githubusercontent.com/3968629/83010880-3e6a4580-a019-11ea-8dfb-fb3a9474dd88.png)
/releases

But it's readable, the most important point - thanks!
