### ISSUE TITLE
Documentation links to in-between majors become obsolete when next major is released

### ISSUE THREAD

**Issue by mhosio** [vaadin/vaadin.com#96]
Can we do smart forwarding in case user tries to access documentation from an older non-supported major version.

For instance https://vaadin.com/docs/v16/flow/advanced/tutorial-i18n-localization.html will just result 404 when it could be easily forwarded to https://vaadin.com/docs/v17/flow/advanced/tutorial-i18n-localization.html

The forwarding logic could be so that if the linked version is not supported anymore, it forwards to latest available / supported upstream major. Today the forwarding logic would be
- 10 -> 10 (no-op)
- 11 -> 14
- 12 -> 14
- 13 -> 14
- 14 -> 14 (no-op)
- 15 -> 17
- 16 -> 17

**Comment by johannesh2** [comment]
I think 10 being an LTS should not forward to 14. Same goes to 14 when nextLTS comes out.

**Comment by mhosio** [comment]
Moved to another repository.

**Comment by jouni** [comment]
But, but… which one @mhosio?! 😅

**Comment by mhosio** [comment]
OK - let me revive and revise this and link to it instead :)

**Comment by paulroemer** [comment]
Removing v16 completely was unintentional and it is now available as a hidden documentation as with other, outdated non-LTS versions: https://vaadin.com/docs/v16
