### ISSUE TITLE
Generated PDF certificates do not contain UTF characters

### ISSUE THREAD

**Issue by mg-dev-fis** [vaadin/vaadin.com#97]
I've passed certification exam and generated PDF file does not contain one of my last name letters (polish **ł** letter):
![image](https://user-images.githubusercontent.com/67044262/94812221-bb0d9600-03f6-11eb-9cea-517339f83629.png)
Should be Głowacki

**Comment by gilberto-torrezan** [comment]
Oh, that's embarrassing. We have Polish colleagues at Vaadin but none of them have the ł letter in their names.

We are investigating the problem and will fix it asap. Most likely it's a font issue on our PDF rendering engine.

Thanks for the report!

**Comment by mg-dev-fis** [comment]
Thanks for such quick response about such low priority issue!

**Comment by paulroemer** [comment]
Hey Marcin,

do you wanne give it a try again?

Cheers,
 Paul

**Comment by mg-dev-fis** [comment]
![image](https://user-images.githubusercontent.com/67044262/95067103-96216780-0703-11eb-87c6-576521f32cf4.png)
Thanks, now is great!

**Comment by mg-dev-fis** [comment]
Well unfortunately, not so perfect:
![image](https://user-images.githubusercontent.com/67044262/95067303-ebf60f80-0703-11eb-8e8b-faa18e30d0ce.png)
Now my cert is on 2 pages ;-)

**Comment by paulroemer** [comment]
Nooooooooooo :) I will take a look!

**Comment by paulroemer** [comment]
Finally, it should work. I just tested the generation of your certificate and it is on one page.

Congrats!

**Comment by mg-dev-fis** [comment]
Yes, it's great now!
