### ISSUE TITLE
Team page sticky header broken with iOS safari

### ISSUE THREAD

**Issue by johanneshayry** [vaadin/vaadin.com#99]
https://user-images.githubusercontent.com/1215482/106857745-3e9f0280-66c9-11eb-9638-9b789a379323.mov

**Comment by paulroemer** [comment]
Hey Johannes,

back that fast? :D

Thanks for reporting, we will take care. As the same hero module is used quite often other pages might be affected, too.

Cheers,
  Paul

**Comment by paulroemer** [comment]
Fixed!
